name: conejoz
description: Dream journal.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1
  http: ^1.1.0
  path_provider: ^2.0.15
  firebase_ui_auth: ^1.6.2
  get: ^4.6.5
  uuid: ^3.0.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  android_12:
    image: assets/images/conejoz-prototype-96-light.png
    icon_background_color: "ffffff"
    image_dark: assets/images/conejoz-prototype-96-dark.png
    icon_background_color_dark: "#000000" 

flutter:
  uses-material-design: true
  assets:
     - assets/images/conejoz-prototype-96-light.png
     - assets/images/conejoz-prototype-96-dark.png

  fonts:
  - family: ConejozLogos
    fonts:
      - asset: assets/fonts/ConejozLogos.ttf
